### ISSUE TITLE
using node-minify as a dep fails to find uglifyjs

### ISSUE THREAD

**Issue by johnc1984** [srod/node-minify#100]
I found a bug with the newer version of npm and this npm package.

The following needs changing to allow your module to work on the older and the newer versions of npm. It depends where npm installs the dependencies.
node_minify.js  at line 97.
```
var nodeModulesV2 = path.normalize(__dirname + '/../../node_modules');
      if( dirExistsSync( path.normalize(__dirname + '/../node_modules/uglify-js/') ) ){
        nodeModulesV2 = path.normalize(__dirname + '/../node_modules');
      }
```
Without this fix uglifyjs and sqwish do not work :(

**Comment by srod** [comment]
It's a known bug because of NPM V3 https://github.com/srod/node-minify/issues/81
If we change that, it will broke on NPM V2 for some users.

I've release a beta version of node-minify V2, can you give it a try ?
I think that I will release soon this V2.

```npm install node-minify@beta```

**Comment by johnc1984** [comment]
Lighting fast response! 
```
  "dependencies": {
  ...
  "node-minify" : "beta"
```
This is all now working on npm 3.10.3.

Cheers
