### ISSUE TITLE
parse error on let = 

### ISSUE THREAD

**Issue by ppetree** [srod/node-minify#1089]
The source code is:
```
  // This is the "report" button
  $("#errReport").on("tap", function(){
    let page = $('#errReport').data('page'); //getter
    report404(page);
  });
```

uglifyjs is failing on this line
let page = $('#errReport').data('page'); //getter
        ^
ERROR: Unexpected token: name «page», expected: punc «;»

**Comment by srod** [comment]
You have to use uglify-es to compress es2015+

https://node-minify.2clics.net/compressors/uglify-es.html
