### ISSUE TITLE
Issue with async on new version ?

### ISSUE THREAD

**Issue by webconsulting** [srod/node-minify#126]
Dear,
i have update node-minify to lastest version but now the css generation seem to be sync.

 I use a simple code : 
compressor.minify({
    compressor: 'sqwish',
    publicFolder: 'public/',
    tempPath: 'tmp/',
    //sync: true,
    input: [
                'library/css/sprite.css',
                'library/css/socialBtn.css',
                'library/css/rightColumn.css',
                'library/css/style.css'
            ],
    output: 'public/library/css/global.css',
    callback: function(err, min){
        if(err !== null){
            logtext('Erreur compressor css front',true);
            log(err,true);
        }
        else {
            logtext('Fichier global.css généré',true);
        }
        nbFileToGenerate--;
        if(nbFileToGenerate === 0){
            deleteTemporaryFile();
        }
    }
});

**Comment by srod** [comment]
I just try with your code, it seems to be fine.
Can you try with this code ?

```javascript
compressor.minify({
  compressor: 'sqwish',
  publicFolder: 'public/',
  tempPath: 'tmp/',
  //sync: true,
  input: [
    'library/css/sprite.css',
    'library/css/socialBtn.css',
    'library/css/rightColumn.css',
    'library/css/style.css'
  ],
  output: 'public/library/css/global.css',
  callback: function(err, min) {
    if (err !== null) {
      logtext('Erreur compressor css front', true);
      log(err, true);
    }
    else {
      logtext('Fichier global.css généré', true);
    }
    nbFileToGenerate--;
    if (nbFileToGenerate === 0) {
      deleteTemporaryFile();
    }
    console.log('=== callback ===');
  }
});

console.log('=== async ===');
```
I've added console.log, can you tell me if you see '=== async ===' before '=== callback ===' or after ?

**Comment by webconsulting** [comment]
You're right. Call are asynch...
I think my process is at 100% and while the compressir work, my website don't respond...

There is a way for configure compressor for use a max cpu % ?
Thanks

**Comment by srod** [comment]
I don't think that's possible with javascript code.
You have to do that in a lower level.

Maybe you can use 'cpulimit' command or 'nice' command on your server ?
With node-minify in a separate node file.

**Comment by webconsulting** [comment]
I'll use cluster module for launch compressor only on master.
i think other cluster'll respond quickly.
Thanks for your help there is no issue with your module ;)
