### ISSUE TITLE
LF / CRLF line ending issues when building

### ISSUE THREAD

**Issue by jonobr1** [srod/node-minify#147]
Hey there,

`node-minify` is awesome and I use it a lot of my projects. Recently I bought a Windows machine and now do cross-platform web development from it and my MacBook. It seems that when I build with `node-minify` on Mac it keeps `LF` line endings, but on Windows throws `CRLF` line endings. This is problematic because Git seems to think there are a number of new changes when there aren't. This even happens when I have `git config --global auto.crlf true`...

Has anyone else run into this issue?

**Comment by srod** [comment]
Hi,

Thank you for your feedback!

Can you provide me a small example of the compressor that you are using?

Maybe I can try to add the node constant `EOL` (https://nodejs.org/api/os.html#os_os_eol)
But I'm not totally sure that's will work, the problem here is that one time you are building on Mac and generate `LF` and after you are building on Windows and generate `CRLF`.
So maybe I can try to add `\n` for all.

I will do some tests on both systems.

**Comment by jonobr1** [comment]
I use it like so: https://github.com/jonobr1/two.js/blob/texture/utils/build.js

One build uses `no-compress` to concatenate all my files in the correct order and the second one uses `gcc`. The node constant `EOL` sounds promising!

**Comment by srod** [comment]
I've setup a test repo: https://github.com/srod/node-minify-test-eol

I don't reproduce the same as you, the repo was created with a MacBook, and after that I tried to build on Windows 10 (a VM with Parallels Desktop).
But Git tells me that there is no changes in the output file.

Can you try it ?
You just need to clone, `npm install` and run `node test.js`

**Comment by jonobr1** [comment]
Sorry for the delay. I'm gonna check this out now!

**Comment by jonobr1** [comment]
Hmm, so after running those commands I get a diff on `public/tempbar.js`
````
D:\node-minify-test-eol>git diff public\tempbar.js
warning: LF will be replaced by CRLF in public/tempbar.js.
The file will have its original line endings in your working directory.
````
This is the opposite of what I want, right? Just to verify my global and local settings for this git project are `auto.crlf true`. I'm so sorry about this confusion...

**Comment by srod** [comment]
But for now I cannot reproduce the same as you, git tells me that there is no changes.
Either on my MacBook and in my Windows 10.
This message: `warning: LF will be replaced by CRLF`, I don't have it, I don't know how you have it.
We must have a different configuration.
I will continue to try some tests.

**Comment by jonobr1** [comment]
Thanks for the support! I'll let you know if I come to any other conclusions as well.

**Comment by jonobr1** [comment]
Hey there. So after additional poking it was actually because files I was feeding into the `compressor` were actually read and written by node's file system *prior* to being sent to you. As a result the issue wasn't with node-minify at all. Thanks for such a great module!
