### ISSUE TITLE
Publish recenter packages to NPM

### ISSUE THREAD

**Issue by nathantaal** [srod/node-minify#1709]
Hi, the latest stable NPM release is a 3.x version. Due to my package manager, I cannot install from git(hub) directly. Could you publish the latest release to NPM?

**Comment by srod** [comment]
Hi, I'm not sure to understand.
Latest version now is 7.1.0 (https://www.npmjs.com/package/@node-minify/core)
Maybe you are on the old version? (https://www.npmjs.com/package/node-minify)
