### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by lemmoor** [srod/node-minify#1797]
I found a broken link on [uglify-js](https://node-minify.2clics.net/compressors/uglify-js/) page. 
Link to `uglify-es` is https://node-minify.2clics.net/compressors/uglify-es.md and I assume it should be https://node-minify.2clics.net/compressors/uglify-es

**Comment by srod** [comment]
Thanks, will fix it!

**Comment by srod** [comment]
Fixed!
