### ISSUE TITLE
node-minify loading time is very long : 6.5s

### ISSUE THREAD

**Issue by doom-fr** [srod/node-minify#275]
Here is my little testing code : 
```
var t=Date.now()
const compressor = require('node-minify');
console.log('node-minify loading time = '+(Date.now()-t)+' ms');
```

Result is :
`node-minify loading time = 6496 ms`

Hardware is raspberry pi 3

**Comment by srod** [comment]
The compression speed depends on the hardware that you are using and also the amount of code that you are compressing.
