### ISSUE TITLE
when i set  compress 'false',it can't skip compressing entirely,make me  crazy

### ISSUE THREAD

**Issue by CrazyApple1** [srod/node-minify#413]
my code is  'ES6'  not ES5
 --------------
that is my setting

---------------

` compressor.minify({
        compressor: 'uglify-es',
        input:  config.input,
        output: config.output_other,
        options: {
          warnings: true, 
          mangle: false, 
          output: {}, 
          compress: false
        },
        callback: function (err, min) {
            console.log('\nDone'.green);
        }
    });`
--------------------
please help me

**Comment by srod** [comment]
Please check all options available for `compress`: https://github.com/mishoo/UglifyJS2/tree/harmony#compress-options
