### ISSUE TITLE
Node.js path error (Windows)

### ISSUE THREAD

**Issue by hanspeter1** [srod/node-minify#55]
Can you change in "libs/node-minifiy.js" the line:

     var prefix = (platform === 'win32') ? 'node ' : process.argv[0] + ' ';

to

    var prefix = (platform === 'win32') ? '"' + process.argv[0].replace(/\\/g,'/') + '" ' : process.argv[0] + ' ';

If node.js is not installed, "node" on cmd can not be found!

**Comment by srod** [comment]
Fixed in 1.0.2, thanks !
