### ISSUE TITLE
cleancss passed more options  but not work

### ISSUE THREAD

**Issue by TearY** [srod/node-minify#61]
hi man , I use clean-css to minify css files  and there are some extra options  like 'advanced : false' for compatibility , and i see your source code and find  you use the CLI to minify the files , but it does work for me , I wonder if there is a way to solve the issues?

**Comment by srod** [comment]
Hi,

You can pass some options to cleancss, like that :

```javascript
new compressor.minify({
    type: 'gcc',
    language: 'ECMASCRIPT5',
    fileIn: 'public/js/jquery-2.0.3.js',
    fileOut: 'public/js-dist/jquery-2.0.3-gcc.js',
    options: ['--option=1', '--option=2'],
    callback: function(err, min){
        console.log(err);
        console.log(min);
    }
});
```

**Comment by TearY** [comment]
thanks a lot
