### ISSUE TITLE
Minification doesn't support synchronous execution

### ISSUE THREAD

**Issue by diogobaeder** [srod/node-minify#64]
Hi,

I need to use node-minify in a project, but it only calls asynchronous execution of child processes to do the actual minification work. This is an issue for me, since in my code structure I need it to be done synchronously.

Is it possible to support something like a `{sync: true}` option, defaulting to `false`, so that it's run synchronously when the client code requests it?

**Comment by srod** [comment]
Hi,

I have published version 1.2.0, can you give it a try ?
So, you have to pass the sync: true option.

```js
new compressor.minify({
  type: 'yui-js',
  publicFolder: 'public/js/',
  fileIn: 'base.js',
  fileOut: 'public/js-dist/base-min-yui-publicfolder.js',
  sync: true,
  callback: function(err, min) {
    console.log('YUI JS with publicFolder option');
    console.log(err);
    //console.log(min);
  }
});
```

Thanks !

**Comment by diogobaeder** [comment]
Hi @srod , thanks a lot for the fix! I unfortunately had to move to UglifyJS directly, but I'll try it in the future if I end up needing it again. :-)

Thanks a bunch for the quick fix, btw! Awesome!

**Comment by kaansoral** [comment]
The sync option doesn't work for me, if I manually block for 2 seconds, I only get one error, the operations succeed, but the the sync option, all the minifications fail

I'm zipping + deleting the minified files afterwards, that's how I can tell whether it's working or not, with the sync:true, the files are long gone although the minification is a previous operation
