### ISSUE TITLE
Any way to use in memory, without writing to a file?

### ISSUE THREAD

**Issue by bitttttten** [srod/node-minify#659]
I would like to be able to do something like:

```
const minify = require('@node-minify/core');

const html = `
<!doctype html>
<html ${htmlAttributes}>
    <head>
        <meta charset="utf-8">
        <!-- ... -->
    </head>
</html>
`

console.log(minify(html))
```

Although on all the examples I see you have to pass in a file and output a file. Is it possible to do it in memory like above?

**Comment by srod** [comment]
Good idea, I will see that 👍

**Comment by tycrek** [comment]
Has any further work been done on this topic?

**Comment by srod** [comment]
Sorry, got no time lately.

**Comment by srod** [comment]
It's live in 5.1.0
You can use it like that:

```javascript
const html = `
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
</html>
`;

minify({
  compressor: htmlMinifier,
  content: html,
  options: {
    minifyJS: false
  },
  callback: function(err, min) {
    console.log('callback min');
    console.log(min);
  }
}).then(function(min) {
  console.log('html min');
  console.log(min);
});
```

You need to pass the compressor according the content (html, css, javascript).
I will see if I can find a solution to detect content type and use defaults compressors.

You can also still pass options to the compressor.

**Comment by tycrek** [comment]
Awesome, thank you!
