### ISSUE TITLE
Searching for cleancss in wrong directory

### ISSUE THREAD

**Issue by ejmurra** [srod/node-minify#75]
Updating from 1.1.0 -> current broke a custom build tool I've been using. It has to do with [this line](https://github.com/srod/node-minify/blob/master/lib/node-minify.js#L97) glob syncing from the current working directory. It should be searching for "**/.bin" relative to __dirname. I'm on deadline right now so I can't fix this for you, currently just reverting to 1.1.0.

**Comment by srod** [comment]
I've released 1.3.5, can you try it ?

**Comment by ejmurra** [comment]
Sorry I wan't able to look into this yesterday. This patch works, thanks!

**Comment by srod** [comment]
I've release a beta version of v2.0.0, can you give it a try ?

```npm install node-minify@beta```

There is some small changes to do : https://github.com/srod/node-minify/blob/develop/Migrate.md

**Comment by ejmurra** [comment]
v2.0.0 beta is working properly with my custom build tool

**Comment by srod** [comment]
Great ! Thank you for your feedback !
