### ISSUE TITLE
still having the same issue.

### ISSUE THREAD

**Issue by NareshBanala** [srod/node-minify#81]
may be you should be checking for entire directory instead of just __dirname + '/../node_modules something like below .

var getPath = function(bin) {
       nodeModulesV2 = path.normalize(__dirname + '/../node_modules/'+bin);
       isNPMv2 = dirExistsSync(nodeModulesV2);
        dirToScan = isNPMv2 ? nodeModulesV2 : '';
        var binPath = glob.sync(dirToScan + '**/.bin/' + bin +
          ((platform === 'win32') ? '.cmd' : ''), {realpath: true})[0];
        console.log(binPath);
        if (!binPath) {
          throw new Error(bin + ' not found !');
        }
        return binPath;

**Comment by srod** [comment]
Can you confirm me that you are using NPM v3 ?
Because if you are in v3, you should't have a ```node_modules``` in node_minify folder.
So ```__dirname + '/../node_modules/``` shouldn't work (it's only for NPM v2).
And for NPM v3, yes, I must check the entire directory.

Can you try to delete your entire ```node_modules``` and run ```npm install``` again ?

And I will try more tests case to see if I found something else.

**Comment by NareshBanala** [comment]
Yes, I am using NPM 3.3.6. I deleted entire node_modules and ran npm install. I see below folders under node_modules\node-minify\node_modules and so I was asking to check entire directory
.bin
.minimist
.mkdirp

**Comment by srod** [comment]
That's weird that you have a node_modules in node_modules\node-minify
Because it's the goal of NPM 3 to flat dependencies and don't have node_modules in packages.

But for now that's what it is doing, scanning the node_modules directory when it's existing.

Can you give me more informations about your configuration ?
What version of Windows ?
What node version ?

**Comment by NareshBanala** [comment]
I am using windows 8 .
Node - v 0.10.32
NPM-3.3.6

I have dead line to have this fixed by tomorrow. Can you please fix this as soon as possible.
worst case I think you can do is to check entire directory to fix this issue.

**Comment by srod** [comment]
But it was ok with version 1.3.2 ? (related to #69)
If so, install this version : npm install node-minify@1.3.2

**Comment by srod** [comment]
And also, can you give me the error message ?
And the call to node-minify (new compressor.minify()) that you are using ?

**Comment by NareshBanala** [comment]
This is the error : 
C:\XYZ\ABC\node_modules\node-minify\lib\node-minify.js:104
          throw new Error(bin + ' not found !');
                ^
Error: sqwish not found !
    at getPath (\C:\XYZ\ABC\node_modules\node-minify\lib\node-minify
.js:104:17)
    at Object.minify.fn.compress (C:\XYZ\ABC\node_modules\node-mini
fy\lib\node-minify.js:137:27)
    at Object.minify (C:\XYZ\ABC\node_modules\node-minify\lib\node-
minify.js:83:10)

-----------------------------------------------------------------------------------------------
,

**Comment by NareshBanala** [comment]
yes, We are using compressor.minify like below
var compressor = require('node-minify');

function compressFiles(filesToCompress, outputFile, compressionType,sourceMap, sourceMapClientPath) {
 new compressor.minify({
    type: compressionType,
    fileIn: filesToCompress,
    fileOut: outputFile,

**Comment by NareshBanala** [comment]
I had  "node-minify": "~1.3.2" in my package.jason and so it is pulling latest version.Now I changed it to use 1.3.2 specifically to make this work.

**Comment by srod** [comment]
I can't reproduce the same error as you.
I've set up a virtual machine with your node and npm version, and it's ok.

I suggest that for now, that you stick with 1.3.2 version.
I'm currently rewriting node-minify to release a 2.0.
And I'm going to do that in total different way.

**Comment by NareshBanala** [comment]
thanks for your response. For now, I am using 1.3.2 version.

**Comment by ianwalter** [comment]
I get the same error on OS X El Capitan.
Node v5.1.1.
NPM 3.3.12.
node-minify 1.3.7.
Reverting to 1.3.2 fixed this issue.

**Comment by srod** [comment]
I've release a beta version of v2.0.0, can you give it a try ?

```npm install node-minify@beta```

There is some small changes to do : https://github.com/srod/node-minify/blob/develop/Migrate.md
