### ISSUE TITLE
Suggestion: JSON minifier?

### ISSUE THREAD

**Issue by OoLunar** [srod/node-minify#887]
Hello! This node module looks very promising. It minifies HTML, CSS and JS, which will prove to be very useful to my project as it minifies on the fly. Could we also get a JSON minifier?

Thank you for your time,
    - Lunar

**Comment by srod** [comment]
Hello, thank you !
Yes, good idea, I will look into it.

**Comment by srod** [comment]
https://www.npmjs.com/package/jsonminify

**Comment by srod** [comment]
Landed in 5.3.0 :tada: 

https://node-minify.2clics.net/compressors/jsonminify.html#usage
