### ISSUE TITLE
Wildcard use in fileIn array

### ISSUE THREAD

**Issue by Lampjaw** [srod/node-minify#89]
So for my application I'd like to have a few .js files that need to go first followed by a wildcard grabbing everything else like this in sync:

    fileIn: ['public/js/base.js', 'public/js/base2.js', 'public/js/**/*.js']

Unfortunately this doesn't work as the fileIn array doesn't support wildcards :(. Then there's the issue of the wild card logic including previously listed files a second time so there would need to be a check to not include the same file twice.

**Comment by srod** [comment]
Can you test with syntax like that for wildcards ?

`public/js/**/*.js`

See : https://github.com/srod/node-minify#using-wildcards

**Comment by Lampjaw** [comment]
Sorry! Forgot github markup used asterisks for formatting.

**Comment by srod** [comment]
Oh, ok, so I will try with your fileIn.

**Comment by srod** [comment]
I've release a beta version of v2.0.0, can you give it a try ?

```npm install node-minify@beta```

There is some small changes to do : https://github.com/srod/node-minify/blob/develop/Migrate.md
