### ISSUE TITLE
Issue with NPM 3 and uglifyjs

### ISSUE THREAD

**Issue by Belleal** [srod/node-minify#91]
When using node-minify with NPM 3 we have issue that it's not able to find the uglifyjs module even though it's in the node_modules folder. After some investigation I found that the problem starts on line **97** in the **node-minify.js** file where it was checking the npm version. I did the following workaround to solve this for us temporary:

```
var nodeModulesV3 = path.normalize(__dirname + '/../../');
var isNPMv2 = dirExistsSync(nodeModulesV2);
var isNPMv3 = ( process.version.indexOf( "v5" ) > -1 );
var dirToScan = isNPMv3 ? nodeModulesV3 : ( isNPMv2 ? nodeModulesV2 : '' );
```

There certainly is a better solution for this, so I don't want to submit this as a fix. Instead please use this issue as notification that the bug exists and needs attention.

**Comment by fnk** [comment]
The same happens with npm 2.14.12...

**Comment by srod** [comment]
Thank you for your notification, it will be fixed in 2.0.0
It happens in the first place because of NPM v3 with its flatten folders.
So I had to do that in a total different way.
I will release 2.0.0 as soon as possible.

**Comment by Belleal** [comment]
Great, thank you.

**Comment by srod** [comment]
I've release a beta version of v2.0.0, can you give it a try ?

```npm install node-minify@beta```

There is some small changes to do : https://github.com/srod/node-minify/blob/develop/Migrate.md
