### ISSUE TITLE
Document the details about the dependencies to be installed

### ISSUE THREAD

**Issue by akshay-since1987** [srod/node-minify#94]
When Trying to use GCC for JS compression I get following error
`{ Error: Command failed: java -jar -Xss2048k "C:\Users\EDUCulture\Desktop\UI Arc
hitecture\node_modules\node-minify\lib/yuicompressor-2.4.7.jar" "C:\Users\EDUCul
ture\Desktop\UI Architecture\build\scripts\script.js" -o "C:\Users\EDUCulture\De
sktop\UI Architecture\build\scripts\script.js" --type js
'java' is not recognized as an internal or external command,
operable program or batch file.`
After a bit of research, I found that the code is dependent on a few things including the compiler from Google Closure. Can you please include the same in Documentation as installation process, please?

**Comment by srod** [comment]
You can find that information at the bottom of the README, "Warning" section :

> It assumes you have Java installed on your environment for both GCC and YUI Compressor. To check, run:
> java -version

It means that you have to install Java and the executable must be in your path.
But maybe it's not clear enough ? You want to add more ?

**Comment by akshay-since1987** [comment]
Can you please add the process to install java and adding path in case its
not already done?

On Sat, May 21, 2016 at 2:25 PM, Rodolphe Stoclin <notifications@github.com>
wrote:

> You can find that information at the bottom of the README, "Warning"
> section :
>
> It assumes you have Java installed on your environment for both GCC and
> YUI Compressor. To check, run:
> java -version
>
> It means that you have to install Java and the executable must be in your
> path.
> But maybe it's not clear enough ? You want to add more ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/srod/node-minify/issues/94#issuecomment-220766916>
>



-- 
Thanks & Regards,
Akshay Khandelwal
(8007024791)

**Comment by srod** [comment]
Sure, I will add some links.
