### ISSUE TITLE
cannot locate to bin folder with npm 3 package structure under Windows 7

### ISSUE THREAD

**Issue by fsworld009** [srod/node-minify#97]
> C:\My\Project\node_modules\node-minify\lib\node-minify.js:104
>           throw new Error(bin + ' not found !');
>           ^
> 
> Error: uglifyjs not found !
>     at getPath (C:\My\Project\node_modules\node-minify\lib\node-minify.js:104:17)
>     at Object.minify.fn.compress (C:\My\Project\node_modules\node-minify\lib\node-minify.js:132:27)
>     at Object.minify (C:\My\Project\node_modules\node-minify\lib\node-minify.js:83:10)
>     at doMinify ( ... 

    
doMinify is my function to minify js files with uglifyjs
    
My code used to work with npm2 package sctructure, today I did a fresh install on npm and node-minify, and then this issue happened.

npm version: 3.8.3
node version: 4.2.1
Operating System: Windows 7 x64
The only package I installed is node-minify.

Please take a look, thanks.

**Comment by srod** [comment]
Can you try the beta version ?

You have to install it: `npm install node-minify@beta`

**Comment by fsworld009** [comment]
@srod
Beta version works fine, but it looks like there are many changes in API in beta version.
Once I updated my doMinify function to match the new API, I can get minified files.

Unfortunately updating doMinify function in production is a issue for our current project configuration, so I think for now I'll stick with master version with npm --legacy-building flag

Thanks for your help.
