### ISSUE TITLE
Error when using gcc-flagfile

### ISSUE THREAD

**Issue by Iangevin** [srod/node-minify#99]
I have this problem when I try using minify with gcc-flagfile as a type with a tempPath. 

I looked at your code and and I think I've found something. Please take in consideration that I am not at all experimented and english isn't my main language.

Line 73   --- this.options = options.options || [];
Line 130 --- this.tempFlagFile = (this.options.tempPath || '') + 'flags_' + new Date().getTime().toString();

tempPath is defined in options, not in options.options which cause to always be undefined.

**Comment by srod** [comment]
Can you provide me the code of the minifier ? (new compressor.minify({}))

**Comment by Iangevin** [comment]
Sure, here is the complete file.
[node-minify.zip](https://github.com/srod/node-minify/files/378142/node-minify.zip)

Line 71 and 131 are the only that I have modified.

**Comment by srod** [comment]
Ho sorry, I was talking about the call to node-minify that you are using.
This lines for example :

```
new compressor.minify({
  type: 'gcc',
  fileIn: 'public/js/base.js',
  fileOut: 'public/js-dist/base-min-gcc.js',
  callback: function(err, min){
    console.log(err);
    //console.log(min);
  }
});
```

**Comment by Iangevin** [comment]
Oh, here you go, but most of my variables are not hard-coded so I don't know if it will help much. I only have this problem on Linux by the way, it seems to run smoothly on Windows.

new compressor.minify({
	type : 'gcc-flagfile',
        fileIn : fileIns,
	fileOut : bundlePath,
	tempPath: '/tmp/',
	callback : this
});

**Comment by srod** [comment]
I don't understand the type 'gcc-flagfile'.
The only options you have is 'gcc'.
Can you try with `type : 'gcc',`
Or maybe I have missed something?

**Comment by srod** [comment]
I'm closing, don't hesitate to reopen if you have more questions later.
